### ISSUE TITLE
我有一个问题，为什么中国人要写英文的文档呢？

### ISSUE THREAD

**Issue by sing1** [uni-cstar/okNet#1]

**Comment by uni-cstar** [comment]
讨论这个问题似乎没什么必要，但还是简单回复下：
1、这不是什么稀奇事，很平常，有很多中国人的库都写了英文文档；
2、这个库的描述不多不复杂，我觉得提供配套的英文文档更多是作为一个基础配套和自己学习英文的一个过程；
3、做这个库的初衷来源于一个英文的issue，那里面讨论者大多使用英文，所以在我做完这个库之后，我想着提供英文版的文档并分享出去
基本上就上面三点
